config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root 'home#index'
  get 'home', to: 'home#index', as: 'home'
  get 'users/sign_up', to: 'users/registrations#new'
  get 'users/sign_in', to: 'users/sessions#new'

  resources :users do
    resources :books do
      member do
        patch :reserve
        put :reserve
        patch :unreserve
        put :unreserve
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :recoverable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :books, dependent: :restrict_with_exception
  has_many :books_on_loan,
           class_name: 'Book',
           foreign_key: :borrower_id,
           inverse_of: :borrower,
           dependent: :restrict_with_exception

  validates :first_name, length: { maximum: 25 }, presence: true
  validates :last_name, length: { maximum: 25 }, presence: true

  def self.create_if_not_exist(data)
    user = User.find_by(email: data[:email])
    return user if user.present?

    User.create(email: data[:email],
                password: Devise.friendly_token[0, 20],
                first_name: data[:first_name],
                last_name: data[:last_name])
  end

  def decorate
    @decorate ||= UserDecorator.new(self)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # rubocop: disable Metrics/AbcSize
  def google_oauth2
    @user = User.create_if_not_exist(request.env['omniauth.auth'].info)

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      # Removing extra as it can overflow some session stores
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
  # rubocop: enable Metrics/AbcSize
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :user_signup_params

  def new
    @user = User.new
    render 'users/new'
  end

  protected

  def user_signup_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :resource_name

  def resource_name
    :user
  end

  def new
    render 'users/new'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  def index
    @users = User.all
  end

  def show
    @my_reservations = current_user.books_on_loan
    @books_reserved_or_taken_from_me = current_user.books
                                                   .where(status: %i[reserved borrowed])
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Your profile has been updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to new_user_registration_path
    flash[:alert] = 'Your account has been deleted.'
  rescue ActiveRecord::DeleteRestrictionError => e
    @user.errors.add(:base, e)
    flash[:alert] = 'You cannot delete your account.'
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :locations)
  end
end

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-group
    = f.input :email, disabled: true, hint: "You cannot change your email.", class: 'form-control'
    = f.input :first_name, class: 'form-control'
    = f.input :last_name, class: 'form-control'
    = f.input :locations,  as: :text, class: 'form-control'

  .form-group
    = f.submit 'Save', class: 'btn btn-primary'
    - cancel_path = @user.new_record? ? user_path(@user) : user_path(@user)
    = link_to 'Cancel', cancel_path, class: 'btn btn-primary'

  = link_to 'Delete', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/users/_left_column.html.haml
.col-6.authentication-landing-column.d-flex.flex-column.align-items-center.justify-content-center
    .display-2.p-2.text-center Book
    .display-2.p-2.text-center Swap
    .display-2.p-2.text-center App

app/views/users/edit.html.haml
%h1 Edit profile
= render 'form'

app/views/users/index.html.haml
%h1.mb-5 Users

.border.rounded-lg.shadow-sm
  %table.table.all-users
    %thead.thead-light
      %tr
        %th.p-3 Name
        %th.p-3 Locations
        %th.p-3

    %tbody
      - @users.each do |user|
        %tr
          %td.p-3= link_to user.decorate.display_full_name, user_path(user)
          %td.p-3= user.locations
          %td.p-3= link_to 'Library', user_books_path(user)

app/views/users/new.html.haml
.row
  = render 'users/left_column'

  .col-6.pt-5.pb-2.pl-5.pr-5
    - if controller_name == 'registrations'
      = render 'registrations'
    - elsif controller_name == 'sessions'
      = render 'sessions'

app/views/users/show.html.haml
- if @user == current_user
  %h1 My profile
- else
  %h1= "#{@user.decorate.display_full_name}'s  profile"

%h5 Email:
%p= @user.email

%h5 Name:
%p= @user.decorate.display_full_name

%h5 Locations:
%p= @user.locations

%h5= link_to 'Library', user_books_path(@user)
%br

- if policy(@user).edit?
  = link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary'

- if @user == current_user
  %h2.mt-5.mb-3 My reservations

  .border.rounded-lg.shadow-sm
    %table.table.my-reservations
      %thead.thead-light
        %tr
          %th.p-3 Book
          %th.p-3 Owner
          %th.p-3 Status
      %tbody
        - @my_reservations.each do |book|
          %tr
            %td.p-3
              .py-1= link_to book.title, user_book_url(book.user, book)
              .text-sm-left.text-secondary= book.author.first_name + ' ' + book.author.last_name
            %td.p-3= link_to book.user.decorate.display_full_name, user_url(book.user)
            %td.p-3
              .d-inline-flex.align-items-center
                .mr-1= status_icon(book)
                = book.status

  %h2.mt-5.mb-3 Reserved from me:

  .border.rounded-lg.shadow-sm
    %table.table.reserved-from-me
      %thead.thead-light
        %tr
          %th.p-3 Book
          %th.p-3 Reserved by
          %th.p-3 Status
      %tbody
        - @books_reserved_or_taken_from_me.each do |book|
          %tr
            %td.p-3
              .py-1= link_to book.title, user_book_url(book.user, book)
              .text-sm-left.text-secondary= book.author.first_name + ' ' + book.author.last_name
            %td.p-3= link_to book.borrower.decorate.display_full_name, user_url(book.borrower)
            %td.p-3
              .d-inline-flex.align-items-center
                .mr-1= status_icon(book)
                = book.status