config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root 'home#index'
  get 'home', to: 'home#index', as: 'home'
  get 'users/sign_up', to: 'users/registrations#new'
  get 'users/sign_in', to: 'users/sessions#new'

  resources :users do
    resources :books do
      member do
        patch :reserve
        put :reserve
        patch :unreserve
        put :unreserve
      end
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  include PgSearch::Model
  include Strippable
  pg_search_scope :search_by_author_title, against: :title, associated_against: { author: %i[first_name last_name] }

  STATUSES_REQUIRING_A_BORROWER = %w[reserved borrowed].freeze
  STRIPPABLE_ATTRIBUTES = %w[title isbn10 isbn13].freeze

  belongs_to :user
  belongs_to :author, dependent: :destroy
  belongs_to :borrower, class_name: 'User', inverse_of: :books_on_loan, optional: true
  enum status: { available: 'available', reserved: 'reserved', borrowed: 'borrowed' }
  accepts_nested_attributes_for :author

  before_validation :strip_input_fields
  before_save :handle_status_and_borrower_correlation

  validates :isbn10, length: { is: 10 },
                     numericality: { only_integer: true, greater_than: 0 },
                     allow_blank: true
  validates :isbn13, length: { is: 13 },
                     numericality: { only_integer: true, greater_than: 0 },
                     allow_blank: true
  validates :title, :status, presence: true

  private

  def handle_status_and_borrower_correlation
    # If the borrower is already set, do not do anything.
    return if STATUSES_REQUIRING_A_BORROWER.include?(status) && borrower.present?

    # If status changed to reserved/borrowed, but no borrower present, it means borrower is the owner
    self.borrower = !STATUSES_REQUIRING_A_BORROWER.include?(status) ? nil : user
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[edit update destroy]
  before_action :set_user

  def index
    @books = @user.books.includes(:author).order(:last_name).references(:author)
  end

  def show
    @book = @user.books.find_by(id: params[:id])
  end

  def new
    @book = @user.books.new
    @book.build_author
    authorize @book
  end

  def edit
    authorize @book
  end

  def create
    @book = @user.books.new(book_params)
    authorize @book

    if @book.save
      redirect_to user_books_path(@user), notice: 'Book has been added successfully.'
    else
      render :new
    end
  end

  def update
    authorize @book

    if @book.update(book_params)
      redirect_to user_book_path(@user, @book), notice: 'Book has been updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    authorize @book
    @book.destroy

    redirect_to user_books_path(@user), notice: 'Book has been deleted.'
  end

  private

  def book_params
    if @user != current_user
      params.require(:book).permit(:status, :borrower_id)
    else
      params.require(:book)
            .permit(:title, :description, :isbn13, :isbn10,
                    :release_date, :status, :borrower_id, author_attributes: %i[id first_name last_name])
    end
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/book_helper.rb
module BookHelper
  AVAILABLE_ICON_PATH = 'media/images/icons8-green-circle-50.png'.freeze
  RESERVED_ICON_PATH = 'media/images/icons8-orange-circle-50.png'.freeze
  BORROWED_ICON_PATH = 'media/images/icons8-red-circle-50.png'.freeze

  def reservation_button_label(book)
    book.status == 'reserved' ? 'Unreserve' : 'Reserve'
  end

  def next_reservation_status(book)
    book.status == 'available' ? 'reserved' : 'available'
  end

  def status_icon(book)
    icon_path = if book.available?
                  AVAILABLE_ICON_PATH
                elsif book.reserved?
                  RESERVED_ICON_PATH
                elsif book.borrowed?
                  BORROWED_ICON_PATH
                end
    return if icon_path.nil?

    image_pack_tag(icon_path, style: 'width: 15px;')
  end
end

app/views/books/_form.html.haml
= simple_form_for [@user, @book] do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-group
    = f.input :title, class: 'form-control'
    = f.simple_fields_for :author do |p|
      = p.input :first_name, class: 'form-control'
      = p.input :last_name, class: 'form-control'
    = f.input :description,  as: :text, class: 'form-control'
    = f.input :release_date, label: 'Published Date', as: :date, start_year: Date.today.year - 60, end_year: Date.today.year, discard_day: true, discard_month: true, class: 'form-control'
    = f.input :isbn13, label: 'ISBN 13', placeholder: 'Numbers only'
    = f.input :isbn10, label: 'ISBN 10', placeholder: 'Numbers only'
    = f.input :status, collection: ['available', 'reserved', 'borrowed']

  .form-group
    = f.submit 'Save', class: 'btn btn-primary'
    - cancel_path = @book.new_record? ? user_books_path(@user) : user_book_path(@user, @book)
    = link_to 'Cancel', cancel_path, class: 'btn btn-primary'

app/views/books/edit.html.haml
%h1 Edit book
= render 'form'

app/views/books/index.html.haml
- if @user == current_user
  %h1.mb-5 My library
- else
  %h1.mb-5= "#{@user.decorate.display_full_name}'s  library"

.border.rounded-lg.shadow-sm
  %table.table.my-books
    %thead.thead-light
      %tr
        %th.p-3 Author
        %th.p-3 Title
        %th.p-3 Status

    %tbody
      - @books.each do |book|
        %tr
          %td.p-3= book.author.first_name + ' ' + book.author.last_name
          %td.p-3= link_to book.title, user_book_path(book.user, book)
          %td.p-3
            .d-inline-flex.align-items-center
              .mr-1= status_icon(book)
              = book.status

app/views/books/new.html.haml
%h1 Add new book
= render 'form'

app/views/books/show.html.haml
%h1= @book.title

%h2= @book.author.first_name + ' ' + @book.author.last_name

%p= @book.description

%p
  .d-inline-flex.align-items-center.mt-2.mb-3
    .mr-1= status_icon(@book)
    .book-status= @book.status

- if policy(@book).show_reservation_btn?
  = simple_form_for [@book.user, @book], method: :put do |f|
    = f.hidden_field :status, value: next_reservation_status(@book)
    = f.hidden_field :borrower_id, value: current_user.id
    = f.submit reservation_button_label(@book), class: 'reservation-btn btn btn-primary'

- if policy(@book).edit?
  = link_to 'Edit', edit_user_book_path(@user, @book), class: 'btn btn-primary'

- if policy(@book).destroy?
  = link_to 'Delete', user_book_path(@user, @book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary'