config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root 'home#index'
  get 'home', to: 'home#index', as: 'home'
  get 'users/sign_up', to: 'users/registrations#new'
  get 'users/sign_in', to: 'users/sessions#new'

  resources :users do
    resources :books do
      member do
        patch :reserve
        put :reserve
        patch :unreserve
        put :unreserve
      end
    end
  end
end

app/views/layouts/_alerts.html.haml
%notice= notice
%alert= alert

app/views/layouts/_sidebar.html.haml
- if current_user.present?
  #sidebar-wrapper.bg-light.border-right
    .sidebar-heading.py-3.px-4= current_user.decorate.display_full_name
    .list-group.list-group-flush
      = link_to 'Home', root_path, class: 'list-group-item list-group-item-action bg-light'
      = link_to 'Add new book', new_user_book_path(current_user), class: 'list-group-item list-group-item-action bg-light'

      = link_to 'My Profile', user_path(current_user), class: 'list-group-item list-group-item-action bg-light'

      = link_to 'My library', user_books_path(current_user), class: 'list-group-item list-group-item-action bg-light'

      = link_to 'All users', users_path, class: 'list-group-item list-group-item-action bg-light'

      = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'list-group-item list-group-item-action bg-light'
    %small.sidebar-footer.py-3.px-4.position-fixed.text-muted
      Icons made by
      %a{href: 'https://icons8.com', target: '_blank'}
        icons8.com

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title BookSwap
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.d-flex
    = render 'layouts/sidebar'
    .container
      = render 'layouts/alerts'
      = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title BookSwap
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield